<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>callback hell</title>
</head>

<body>
    <script>
        // Callback hell, also known as "Pyramid of Doom," is a situation in asynchronous programming where multiple nested callbacks create code that is hard to read, understand, and maintain. 
        // It typically occurs when dealing with a series of asynchronous operations that depend on the results of previous operations.
        //  This nesting of callbacks can lead to code that looks like a pyramid, making it challenging to manage.


        function asyncOperation1(callback) {
            setTimeout(function () {
                console.log('Async Operation 1');
                callback();
            }, 1000);
        }

        function asyncOperation2(callback) {
            setTimeout(function () {
                console.log('Async Operation 2');
                callback();
            }, 500);
        }

        function asyncOperation3(callback) {
            setTimeout(function () {
                console.log('Async Operation 3');
                callback();
            }, 800);
        }
        
// callBack Hell
        asyncOperation1(function () {
            asyncOperation2(function () {
                asyncOperation3(function () {
                    console.log('All operations are done.');
                });
            });
        });


// Using .then and .catch:
        function asyncOperation1() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log('Async Operation 1');
                    resolve();
                }, 1000);
            });
        }

        function asyncOperation2() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log('Async Operation 2');
                    resolve();
                }, 500);
            });
        }

        function asyncOperation3() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log('Async Operation 3');
                    resolve();
                }, 800);
            });
        }

        asyncOperation1()
            .then(() => asyncOperation2())
            .then(() => asyncOperation3())
            .then(() => {
                console.log('All operations are done.');
            })
            .catch((error) => {
                console.error('An error occurred:', error);
            });

// Using async/await:
        async function runAsyncOperations() {
            try {
                await asyncOperation1();
                await asyncOperation2();
                await asyncOperation3();
                console.log('All operations are done.');
            } catch (error) {
                console.error('An error occurred:', error);
            }
        }

        runAsyncOperations();

    </script>
</body>

</html>